/************************************************************************************************************
 * @(#) KnoGenerationDetails.java   10 Feb 2016
 * 
 *
 *************************************************************************************************************/
package com.tcs.djb.model;

/**
 * <p>
 * <code>KnoGenerationDetails</code> is the model class which contains all the
 * jsp variables specific for New Connection KNO and Bill Generation
 * </p>
 * 
 * @since 10-FEB-2016
 * @author Rajib Hazarika (Tata Consultancy Services)
 * @history Sanjay on 17-03-2016 edited to add plot area as per jTrac DJB-4418
 * @history: On 01-APR-2016 Rajib Hazarika (682667) added variables purpose of
 *           Application Change status Flag as per JTrac DJB-4429
 * @history Lovely on 27-08-2016 added variables as per JTrac DJB-4541 ,Open
 *          project-1443.
 */
public class KnoGenerationDetails {
	/**
	 * variable to Store Account generated by value.
	 */
	private String acctGenBy;
	/**
	 * variable to Store Account Id.
	 */
	private String acctId;
	/**
	 * variable to Store Applicant's Address.
	 */
	private String address;

	/**
	 * variable to Store Applicable Additional Charges/pending Charges .
	 */
	private String addtionalCharge;
	/**
	 * variable to Store Applicable Civil Construction Charges.
	 */
	private String applCivilConstChrg;

	/**
	 * variable to Store ARN Generated by.
	 */
	private String arnGenBy;

	/**
	 * variable to Store ARN Generated by.
	 */
	private String arnNo;

	/**
	 * variable to Store Bank Acct id.
	 */
	private String bankAcct;

	/**
	 * variable to Store Bank Branch.
	 */
	private String bankBranch;

	/**
	 * variable to Store Bank Name.
	 */
	private String bankMicr;

	/**
	 * variable to Store Bank Name.
	 */
	private String bankName;

	/**
	 * variable to Store Bill generated by value.
	 */
	private String billGenBy;
	/**
	 * variable to Store BillId.
	 */
	private String billId;
	/**
	 * variable to Store Applicant's Name.
	 */
	private String consumerName;

	/**
	 * variable to Store Customer Colony Value which is not in use today.
	 */
	private String custColony;

	/**
	 * variable to Store Development Charge Colony for Sewer.
	 */
	private String devChrgColonySew;

	/**
	 * variable to Store Development Charge Colony for Water.
	 */
	private String devChrgColonyWat;

	/**
	 * variable to Store Development Charge Colony for Water and Sewer.
	 */
	private String devChrgColonyWatSew;

	/**
	 * variable to Store Notification date for Sewer Development Charges.
	 */
	private String devChrgNotifyDtSewer;
	/**
	 * variable to Store Development Charge Notification Date for Water.
	 */
	private String devChrgNotifyDtWat;

	/**
	 * variable to Store DJb Employee Rebate Applicable or not.
	 */
	private String djbEmpRbtAppl;

	/**
	 * variable to Store Customer date of Application.
	 */
	private String dtOfAppl;

	/**
	 * variable to Store DJb Employee Retirement Date.
	 */
	private String dtOfRet;

	/**
	 * variable to Store DJb Employee ID.
	 */
	private String empId;

	/**
	 * variable to Store File No.
	 */
	private String fileNo;

	/**
	 * variable to Store is Documents verified by User.
	 */
	private String isDocVerified;

	/**
	 * variable to Store Is Occupier Security .
	 */
	private String isOccupierSecurity;

	/**
	 * variable to Store Unauthorized usage detected at premise.
	 */
	private String isUnAuthorisedUsage;

	/**
	 * variable to Store Is water being used in civil construction for the
	 * premises.
	 */
	private String isWatUsedForPrem;

	/**
	 * variable to Store length of road to be cut for Sewer.
	 */
	private String lengthOfRoadForSewer;

	/**
	 * variable to Store length of road to be cut for water.
	 */
	private String lengthOfRoadForWater;

	/**
	 * variable to Store Applicant's Phone No.
	 */
	private String mobNo;
	/**
	 * variable to Store Unique MR key value .
	 */
	private String mrkey;
	/* End : Edited by Sanjay Kumar Das (1033846) as per JTrac DJB-4408 */
	/**
	 * variable to Store meter security charge .
	 */
	private String mtrSecurityCharge;

	/**
	 * variable to Store Applicable no. of yrs for which unauthorized usage
	 * penalty is charged .
	 */
	private String noOfYrForUnauthPenlaty;
	/**
	 * variable to Store Field Not to be used(Please provide 0 as default
	 * mandatory value).
	 */
	private String notToBeUsed;

	/**
	 * variable to Store Person Id.
	 */
	private String perId;

	/* Start : Edited by Sanjay Kumar Das (1033846) as per JTrac DJB-4408 */
	/**
	 * variable to Store Plot Area value .
	 */
	private String plotArea;
	/**
	 * variable to Store Plot Area value .
	 */
	private String plotAreaOld;

	/**
	 * variable to Store Preferred mode of payment.
	 */
	private String prefModeOfPayment;

	/**
	 * variable to Store Application purpose.
	 */
	private String purposeOfAppl;
	/**
	 * variable to Store Application purpose Changed Flag.
	 */
	private String purposeOfApplChngFlag;

	/**
	 * variable to Store Applicable Road Restoration Charges for Sewer .
	 */
	private String roadRestChrgForSewer;

	/**
	 * variable to Store Applicable Road Restoration Charges for Water .
	 */
	private String roadRestChrgForWater;

	/**
	 * variable to Store Sewer Development Charge Applicability.
	 */
	private String sewDevChrgAppl;

	/**
	 * variable to Store Sewer Development Charge Notify Date Not used.
	 */
	private String sewDevChrgNotifyDt;

	/**
	 * variable to Store Sewerage Technical Feasibility.
	 */
	private String sewTechFeasibility;

	/**
	 * variable to Store Size of meter.
	 */
	private String sizeOfMtr;

	/**
	 * variable to Store Status Code of ARN/File.
	 */
	private String statusCd;

	/**
	 * variable to Store New Connection To Do Form Field value.
	 */
	private String toDoField;

	/**
	 * variable to Store Trade security charge .
	 */
	private String tradeSecurityCharge;

	/**
	 * variable to Store Applicable unauthorized Usage Penalty based on
	 * estimated consumption.
	 */
	private String unauthPenlatyAmt;

	/**
	 * variable to Store Water Development Charge Applicability.
	 */
	private String watDevChrgAppl;

	/**
	 * variable to Store Water Development Charge Notify Date Not used.
	 */
	private String watDevChrgNotifyDt;

	/**
	 * variable to Store Water Technical Feasibility.
	 */
	private String watTechFeasibility;

	/**
	 * variable to Store Zro Location.
	 */
	private String zroCd;

	// Start: Added by Lovely (986018) as per JTrac DJB-4541 ,Open project-1443.
	/**
	 * variable to Store online status for online consumers.
	 */
	private String onlineStatus;
	public String getOnlineStatus() {
		return onlineStatus;
	}

	public void setOnlineStatus(String onlineStatus) {
		this.onlineStatus = onlineStatus;
	}

	// End: Added by Lovely (986018) as per JTrac DJB-4541 ,Open project-1443.
	public String getAcctGenBy() {
		return acctGenBy;
	}

	public String getAcctId() {
		return acctId;
	}

	public String getAddress() {
		return address;
	}

	public String getAddtionalCharge() {
		return addtionalCharge;
	}

	public String getApplCivilConstChrg() {
		return applCivilConstChrg;
	}

	public String getArnGenBy() {
		return arnGenBy;
	}

	public String getArnNo() {
		return arnNo;
	}

	public String getBankAcct() {
		return bankAcct;
	}

	public String getBankBranch() {
		return bankBranch;
	}

	public String getBankMicr() {
		return bankMicr;
	}

	public String getBankName() {
		return bankName;
	}

	public String getBillGenBy() {
		return billGenBy;
	}

	public String getBillId() {
		return billId;
	}

	public String getConsumerName() {
		return consumerName;
	}

	public String getCustColony() {
		return custColony;
	}

	public String getDevChrgColonySew() {
		return devChrgColonySew;
	}

	public String getDevChrgColonyWat() {
		return devChrgColonyWat;
	}

	public String getDevChrgColonyWatSew() {
		return devChrgColonyWatSew;
	}

	public String getDevChrgNotifyDtSewer() {
		return devChrgNotifyDtSewer;
	}

	public String getDevChrgNotifyDtWat() {
		return devChrgNotifyDtWat;
	}

	public String getDjbEmpRbtAppl() {
		return djbEmpRbtAppl;
	}

	public String getDtOfAppl() {
		return dtOfAppl;
	}

	public String getDtOfRet() {
		return dtOfRet;
	}

	public String getEmpId() {
		return empId;
	}

	public String getFileNo() {
		return fileNo;
	}

	public String getIsDocVerified() {
		return isDocVerified;
	}

	public String getIsOccupierSecurity() {
		return isOccupierSecurity;
	}

	public String getIsUnAuthorisedUsage() {
		return isUnAuthorisedUsage;
	}

	public String getIsWatUsedForPrem() {
		return isWatUsedForPrem;
	}

	public String getLengthOfRoadForSewer() {
		return lengthOfRoadForSewer;
	}

	public String getLengthOfRoadForWater() {
		return lengthOfRoadForWater;
	}

	public String getMobNo() {
		return mobNo;
	}

	public String getMrkey() {
		return mrkey;
	}

	public String getMtrSecurityCharge() {
		return mtrSecurityCharge;
	}

	public String getNoOfYrForUnauthPenlaty() {
		return noOfYrForUnauthPenlaty;
	}

	public String getNotToBeUsed() {
		return notToBeUsed;
	}

	public String getPerId() {
		return perId;
	}

	public String getPlotArea() {
		return plotArea;
	}

	/* End : Edited by Sanjay Kumar Das (1033846) as per JTrac DJB-4408 */
	public String getPlotAreaOld() {
		return plotAreaOld;
	}

	/* Start : Edited by Sanjay Kumar Das (1033846) as per JTrac DJB-4408 */

	public String getPrefModeOfPayment() {
		return prefModeOfPayment;
	}

	public String getPurposeOfAppl() {
		return purposeOfAppl;
	}

	public String getPurposeOfApplChngFlag() {
		return purposeOfApplChngFlag;
	}

	public String getRoadRestChrgForSewer() {
		return roadRestChrgForSewer;
	}

	public String getRoadRestChrgForWater() {
		return roadRestChrgForWater;
	}

	public String getSewDevChrgAppl() {
		return sewDevChrgAppl;
	}

	public String getSewDevChrgNotifyDt() {
		return sewDevChrgNotifyDt;
	}

	public String getSewTechFeasibility() {
		return sewTechFeasibility;
	}

	public String getSizeOfMtr() {
		return sizeOfMtr;
	}

	public String getStatusCd() {
		return statusCd;
	}

	public String getToDoField() {
		return toDoField;
	}

	public String getTradeSecurityCharge() {
		return tradeSecurityCharge;
	}

	public String getUnauthPenlatyAmt() {
		return unauthPenlatyAmt;
	}

	public String getWatDevChrgAppl() {
		return watDevChrgAppl;
	}

	public String getWatDevChrgNotifyDt() {
		return watDevChrgNotifyDt;
	}

	public String getWatTechFeasibility() {
		return watTechFeasibility;
	}

	public String getZroCd() {
		return zroCd;
	}

	public void setAcctGenBy(String acctGenBy) {
		this.acctGenBy = acctGenBy;
	}

	public void setAcctId(String acctId) {
		this.acctId = acctId;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public void setAddtionalCharge(String addtionalCharge) {
		this.addtionalCharge = addtionalCharge;
	}

	public void setApplCivilConstChrg(String applCivilConstChrg) {
		this.applCivilConstChrg = applCivilConstChrg;
	}

	public void setArnGenBy(String arnGenBy) {
		this.arnGenBy = arnGenBy;
	}

	public void setArnNo(String arnNo) {
		this.arnNo = arnNo;
	}

	public void setBankAcct(String bankAcct) {
		this.bankAcct = bankAcct;
	}

	public void setBankBranch(String bankBranch) {
		this.bankBranch = bankBranch;
	}

	public void setBankMicr(String bankMicr) {
		this.bankMicr = bankMicr;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public void setBillGenBy(String billGenBy) {
		this.billGenBy = billGenBy;
	}

	public void setBillId(String billId) {
		this.billId = billId;
	}

	public void setConsumerName(String consumerName) {
		this.consumerName = consumerName;
	}

	public void setCustColony(String custColony) {
		this.custColony = custColony;
	}

	public void setDevChrgColonySew(String devChrgColonySew) {
		this.devChrgColonySew = devChrgColonySew;
	}

	public void setDevChrgColonyWat(String devChrgColonyWat) {
		this.devChrgColonyWat = devChrgColonyWat;
	}

	public void setDevChrgColonyWatSew(String devChrgColonyWatSew) {
		this.devChrgColonyWatSew = devChrgColonyWatSew;
	}

	public void setDevChrgNotifyDtSewer(String devChrgNotifyDtSewer) {
		this.devChrgNotifyDtSewer = devChrgNotifyDtSewer;
	}

	public void setDevChrgNotifyDtWat(String devChrgNotifyDtWat) {
		this.devChrgNotifyDtWat = devChrgNotifyDtWat;
	}

	public void setDjbEmpRbtAppl(String djbEmpRbtAppl) {
		this.djbEmpRbtAppl = djbEmpRbtAppl;
	}

	public void setDtOfAppl(String dtOfAppl) {
		this.dtOfAppl = dtOfAppl;
	}

	public void setDtOfRet(String dtOfRet) {
		this.dtOfRet = dtOfRet;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public void setIsDocVerified(String isDocVerified) {
		this.isDocVerified = isDocVerified;
	}

	public void setIsOccupierSecurity(String isOccupierSecurity) {
		this.isOccupierSecurity = isOccupierSecurity;
	}

	public void setIsUnAuthorisedUsage(String isUnAuthorisedUsage) {
		this.isUnAuthorisedUsage = isUnAuthorisedUsage;
	}

	public void setIsWatUsedForPrem(String isWatUsedForPrem) {
		this.isWatUsedForPrem = isWatUsedForPrem;
	}

	public void setLengthOfRoadForSewer(String lengthOfRoadForSewer) {
		this.lengthOfRoadForSewer = lengthOfRoadForSewer;
	}

	public void setLengthOfRoadForWater(String lengthOfRoadForWater) {
		this.lengthOfRoadForWater = lengthOfRoadForWater;
	}

	public void setMobNo(String mobNo) {
		this.mobNo = mobNo;
	}

	public void setMrkey(String mrkey) {
		this.mrkey = mrkey;
	}

	public void setMtrSecurityCharge(String mtrSecurityCharge) {
		this.mtrSecurityCharge = mtrSecurityCharge;
	}

	public void setNoOfYrForUnauthPenlaty(String noOfYrForUnauthPenlaty) {
		this.noOfYrForUnauthPenlaty = noOfYrForUnauthPenlaty;
	}

	public void setNotToBeUsed(String notToBeUsed) {
		this.notToBeUsed = notToBeUsed;
	}

	public void setPerId(String perId) {
		this.perId = perId;
	}

	public void setPlotArea(String plotArea) {
		this.plotArea = plotArea;
	}

	/* Start : Edited by Sanjay Kumar Das (1033846) as per JTrac DJB-4408 */

	public void setPlotAreaOld(String plotAreaOld) {
		this.plotAreaOld = plotAreaOld;
	}

	/* End : Edited by Sanjay Kumar Das (1033846) as per JTrac DJB-4408 */
	public void setPrefModeOfPayment(String prefModeOfPayment) {
		this.prefModeOfPayment = prefModeOfPayment;
	}

	public void setPurposeOfAppl(String purposeOfAppl) {
		this.purposeOfAppl = purposeOfAppl;
	}

	public void setPurposeOfApplChngFlag(String purposeOfApplChngFlag) {
		this.purposeOfApplChngFlag = purposeOfApplChngFlag;
	}

	public void setRoadRestChrgForSewer(String roadRestChrgForSewer) {
		this.roadRestChrgForSewer = roadRestChrgForSewer;
	}

	public void setRoadRestChrgForWater(String roadRestChrgForWater) {
		this.roadRestChrgForWater = roadRestChrgForWater;
	}

	public void setSewDevChrgAppl(String sewDevChrgAppl) {
		this.sewDevChrgAppl = sewDevChrgAppl;
	}

	public void setSewDevChrgNotifyDt(String sewDevChrgNotifyDt) {
		this.sewDevChrgNotifyDt = sewDevChrgNotifyDt;
	}

	public void setSewTechFeasibility(String sewTechFeasibility) {
		this.sewTechFeasibility = sewTechFeasibility;
	}

	public void setSizeOfMtr(String sizeOfMtr) {
		this.sizeOfMtr = sizeOfMtr;
	}

	public void setStatusCd(String statusCd) {
		this.statusCd = statusCd;
	}

	public void setToDoField(String toDoField) {
		this.toDoField = toDoField;
	}

	public void setTradeSecurityCharge(String tradeSecurityCharge) {
		this.tradeSecurityCharge = tradeSecurityCharge;
	}

	public void setUnauthPenlatyAmt(String unauthPenlatyAmt) {
		this.unauthPenlatyAmt = unauthPenlatyAmt;
	}

	public void setWatDevChrgAppl(String watDevChrgAppl) {
		this.watDevChrgAppl = watDevChrgAppl;
	}

	public void setWatDevChrgNotifyDt(String watDevChrgNotifyDt) {
		this.watDevChrgNotifyDt = watDevChrgNotifyDt;
	}

	public void setWatTechFeasibility(String watTechFeasibility) {
		this.watTechFeasibility = watTechFeasibility;
	}

	public void setZroCd(String zroCd) {
		this.zroCd = zroCd;
	}
}
